# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'app/assets/*'	
    - 'vendor/**/*'
    - 'tmp/**/*'

StringLiterals:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/Tab:
  Enabled: false
