# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4981508a8ae5fd1237813eae9f33fb2a5b6278a22dc9f37c4b7a604a6badf94d6d675c8b29980fe9dab4ae6976d8b033b243f74808c53ab3777fd914d6515c78

test:
  secret_key_base: 9bdc15c72a45f9f0e7f5ab414928ee916abd51ff86344f678b7c2d0df2917f7196f7a3e4d2d9737698698175d7bbec3fffdcb160a71d6705a5616ce61a6a4849

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
